# Generated by Django 4.0 on 2021-12-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Enter a language', to='catalog.Language'),
        ),
    ]
