# Generated by Django 4.0 on 2021-12-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_author_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='n/a', help_text='Enter a language (e.g. English)', max_length=200, verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
