# Generated by Django 4.0 on 2021-12-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
